kind: Deployment
apiVersion: apps/v1
metadata:
  name: ui-dist-builder
  labels:
    app: ui-dist-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-dist-builder
  template:
    metadata:
      labels:
        app: ui-dist-builder
    spec:
      volumes:
        - name: ui-claim
          persistentVolumeClaim:
            claimName: "ui-pv-claim"
      containers:
        - resources: {}
          name: ui
          ports:
            - containerPort: 4200
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: ui-claim
              mountPath: /home/ui
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 4200
            timeoutSeconds: 1
          terminationMessagePolicy: File
          terminationMessagePath: /dev/termination-log
          image: UI_IMAGE
          env:
            - name: CONFIG
              value: "argo"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate
