apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: ui-dist-builder
spec:
  selector:
    app: ui-dist-builder
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
